"""Add fields for failure handling

Revision ID: 61cd0b2e67e5
Revises: 0b2a1d619939
Create Date: 2025-07-02 21:42:15.906506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cd0b2e67e5'
down_revision: Union[str, Sequence[str], None] = '0b2a1d619939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('current_attempt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('jobs', sa.Column('run_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_jobs_run_at'), 'jobs', ['run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_run_at'), table_name='jobs')
    op.drop_column('jobs', 'run_at')
    op.drop_column('jobs', 'current_attempt')
    op.drop_column('jobs', 'last_error')
    # ### end Alembic commands ###
