"""Add idempotency key to jobs

Revision ID: c975bc8808d9
Revises: 4a87fa851ace
Create Date: 2025-07-02 22:59:46.590132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c975bc8808d9'
down_revision: Union[str, Sequence[str], None] = '4a87fa851ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###
